### PR TITLE
Implement the Plugin sql updates

### PR DESCRIPTION
**Pull request by saman222**
I checked the JCB codes and tried to implement the plugin sql updates section , which did not work , according to the JCB structure

### CODE REVIEW

**Comment by Llewellynvdm** [comment]
I have looked over the code, and for the most part you did a great job... but I think there is a simpler way, that does not need use messing with some of the function you touched.

I am a little over occupied at the moment, but will give it another look the second or third week or so in the new year.

**Comment by saman222** [comment]
I'm trying to get a professional membership. Do you accept this commit of mine as my second commit, regardless of whether you apply it or not?
I spend many time to do this commit.

**Comment by Llewellynvdm** [comment]
I will in good faith give you access trusting that you will continue to help and contribute to JCB ;) happy new year!

**Comment by saman222** [comment]
Thank you very much @Llewellynvdm .
I was looking forward to this moment. I will definitely try to play an active role. How can i access to pro member? in git.vdm ?

**Comment by saman222** [comment]
hi @Llewellynvdm 
if you give me a little guidance, i can implement Plugin sql updates with your standard path and code style.

**Pull request closed without merging**
