### PR TITLE
Major Upgrade away from repeatable fields in Joomla component view.

### PR DESCRIPTION
**Pull request by Llewellynvdm**
- Added status, copy and delete sync between admin_view linked views (admin_fields, admin_fields_conditions).
- Added notice of language (tanslations) added or not added with details to compiler
- Resolved gh-146 compiler error on joined db in dinamic get thanks to @mwweb & @ro-ot
- Resolved gh-147 by adding the sort of fields back into the save method
- Resolved gh-144 to ensure that the published tab (fields overwriting and adding) option is available again.
- Resolved gh-145 by moving the subforms to their own tab in dynamic get view
- Converted all repeatable fields to subform fields in Joomla component view
- Moved 9 subforms and other fields to their own table and view (decopuling them fom Joomla component view), that means we added 9 more views and tables to JCB
- Added all the ajax for buttons and display views to Joomla component view
- Added tmp scripts all across the new areas with subforms to ensure all repeatable fields are converted. Will be removed in v2.7.0
- Added synced copy, change state and delete in Joomla components view in relation to all tables linked to it (same as with admin views)

### CODE REVIEW

**Comment by ro-ot** [comment]
I tried to copy a Joomla Component view

```
Catchable fatal error: Object of class stdClass could not be converted to string in /home/root/libraries/src/Filter/InputFilter.php on line 345
```
So it seems there is a error in your copy method.

**Comment by mwweb** [comment]
My preliminary testing this build appears to be working correctly.

**Comment by Llewellynvdm** [comment]
No the build/compiler does not work. **CAUTION** the compiler has not been updated.

**Comment by Llewellynvdm** [comment]
Just the data have been moved and the views setup and all the nice **UI** stuff :+1:

**Comment by mwweb** [comment]
I realize that. I'll test the compiler when it's ready. I tested by adding a publishing tab, and placed a field in the publishing tab. I will see if it properly places that field in the publishing tab when compile is working, which would resolve one of the issue suggestions.

**Comment by Llewellynvdm** [comment]
Ya all the last few issues where addressed in the compiler, but not the transition to subforms in the joomla_component view.

I think this release is going to be the biggest yet with over 35k new lines of code.

**Comment by mwweb** [comment]
With such major changes, is just a minor incremental version change appropriate? With such major changes, would it, possibly, be more appropriate to have this version as 2.6.0? Then work up from there, then for the Joomla! 4 version, start at 3.0? Just thinking out loud on this. I went around and around with the Joomla Devs on something similar when they released J! 1.6 (which they admitted later should have been 2.0, which is what I was saying to them).

**Comment by Llewellynvdm** [comment]
I think the release should be v2.6.0

Then the compiler and all will be ready and working. So yes we should give a clear heads-up on this release. I pushed it to v2.5.9 but I was intending to bump to 2.6 before we let this one out :+1:

**Comment by Llewellynvdm** [comment]
Okay I have managed to do the complete update, everything should now work as expected.

- The whole new Joomla Component View is ready
- The compiler is ready
- The export of JCB packages is ready
- The import of JCB package

@ro-ot  & @mwweb please test and let me know if you find any issues.

**Comment by mwweb** [comment]
I ran a test and it compiled fine. The custom field that I added to tab "publishing" is showing on the Publishing tab in the admin view. One thing I think we may want to point out of people is that if they want to add to that tab, they need to keep the position to Left in Tab. 

Export and Import of the component appears to be working as well.

**Comment by Llewellynvdm** [comment]
Try adding it to the right and then compile the component, you will see a message :)

**Comment by mwweb** [comment]
I did that initially and there was a message that the position didn't exist. That's where i moved it and recompiled.

**Comment by Llewellynvdm** [comment]
Yes, is that not enough?

**Comment by Llewellynvdm** [comment]
Can you do some test on exporting and importing of JCB packages?

**Comment by mwweb** [comment]
I guess we can leave the note as is. If there is any confusion/questions we can add to the note later. I dobt know how many will use the ability to add to the publishing tab. 

I tested exporting and importing one component, and it appears to have worked flawlessly. I'll create a whole new install today and test more.

**Comment by mwweb** [comment]
OK. I did a complete export of my components, and imported into a brand new test site. It looks like FTPs didn't export, and out of 37 layouts only 1 is in the new site.

**Comment by Llewellynvdm** [comment]
Okay the FTP don't export by default, as a security measure.

I will check the layouts issue that is weird.

Thanks!

**Comment by Llewellynvdm** [comment]
It is weird because it is in an area I did not change in this update... I just tested it again my self with the Sermon Distributor component and it moved all the layouts as expected. I will keep looking...

Just that you know the export will only export layouts linked in **templates** or **site_views** or **custom_admin_views** or other layouts of course that are linked to components. IF not linked to components it will not export it. Not that I think this is the case with you... just want to make sure we are clear on that implementation principle.

**Comment by Llewellynvdm** [comment]
@mwweb have you been able to resolve the issues you mentioned. We are about ready to let this upgrade merge with the core.

**Comment by mwweb** [comment]
I just ran another test. The component that I am exporting is my component that is now "live". There are multiple admin views, several site views, several templates being called in the site views, and several layouts being called from the templates.

Once again, it looks like all the admin views, sites views, and templates are being exported, but not the layouts.

I event tested with doing an export of Sermon Distributor, then importing. The same thing happens: only Series Table Row imports.

**Comment by Llewellynvdm** [comment]
This is strange, I am not seeing the same issue at all, in fact this JCB seems to work more effectively then any of the version before.

Would you mind giving me the Sermon Distributor JCB package that you have exported. So I can try import it on my blank install to see what happens.

**Comment by mwweb** [comment]
Here you go.

[JCB_sermondistributor.zip](https://github.com/vdm-io/Joomla-Component-Builder/files/1428424/JCB_sermondistributor.zip)

**Comment by Llewellynvdm** [comment]
Can you please email me the key?

**Comment by mwweb** [comment]
I had to dig through all my old emails to find your email address. I just sent the package and key to your joomla email address.

**Comment by Llewellynvdm** [comment]
I still did not receive your email... but I found the issue. Please test and let me know.

Just **note** the problem was with the exporter not the importer :+1:

**Comment by Llewellynvdm** [comment]
I was not seeing the error before, since I was using old exporter JCB packages. But I think it is resolved now.

**Comment by Llewellynvdm** [comment]
We are about ready to publish this.... just need you to verify that the issue is resolved.

**Comment by mwweb** [comment]
That looks like it resolved the issue.

**Comment by mwweb** [comment]
I need to run 1 more test for you. When attempting to compile, I received an error: 0 Call to undefined function bcadd()

**Comment by mwweb** [comment]
Yes, it looks like there is an error in the compiler in regards to bcadd.

jcb_error

**Comment by mwweb** [comment]
Update on the above error: the error ONLY occurs in PHP 7, not in PHP 5. So, there appears to be something that is not compatible with PHP 7 in the compiler.

**Comment by Llewellynvdm** [comment]
This is a function for calculations that should be turned on in PHP.
http://php.net/manual/en/function.bcadd.php

**Pull request merged**
