### PR TITLE
Editors xtd

### PR DESCRIPTION
**Pull request by saman222**

### CODE REVIEW

**Comment by saman222** [comment]
please ignore this commite: [c37dfc0](https://github.com/vdm-io/Joomla-Component-Builder/pull/871/commits/c37dfc0b21abe194a30e626fc79dc059fe2d5c54)
i wanted to only send this commite : [d57f35f](https://github.com/vdm-io/Joomla-Component-Builder/pull/871/commits/d57f35fc006ce1dc189bf5af30358e6cf2e8891c)
But I made a small mistake in sending commit

**Comment by Llewellynvdm** [comment]
@saman222 any feedback on my previous request?

**Comment by saman222** [comment]
Hi @Llewellynvdm , I hope you are well.

To create a plugin from the editors-xtd group (add a button to the editor), I went to the jcb plugin section and went through the steps of creating this plugin. After compiling, installing and activating that plugin, I went to the Joomla article creation page to see the result. To see if the button I wanted was added to that page's editor or not, I got an error (syntax error, unexpected '-', expecting '{') which is actually a syntax error and may not be a direct JCB bug . After searching, I realized that the name of the main class of Joomla editors-xtd plugins should be "plgButton<PluginName>" instead of "plgEditors-xtd<PluginName>"

### Summary of Changes
In the setJoomlaPlugin function in the Get class (/public_html/administrator/components/com_componentbuilder/helpers/compiler/a_Get.php path), almost on line 10152, the name of the plugin class is created. I put the creation of the plugin class name in a function called createPluginClassName in the path (/administrator/components/com_componentbuilder/helpers/componentbuilder.php) which checks if the plugin group was editors-xtd to name the class as "plgButton <PluginName>"

### Testing Instructions
Making a plugin with the editors-xtd group

### Expected result
Build a plugin with the editors-xtd group and the class name "plgButton<PluginName>"

### Actual result
Build a plugin with the editors-xtd group and the class name "plgEditors-xtd<PluginName>" and error

**Comment by Llewellynvdm** [comment]
Okay so I have been working on moving things to library classes, basically moving to J4 we need namespacing everywhere... so I am starting with the basics first, and just for JCB at this time, it will not yet effect other components build with JCB.

So I will manually add these Plugin naming method to its own utilities class and I should be pushing this up soon. So thanks @saman222  for the code I will use it... keep a lookout to the new way we are going... the place to watch is going to be in libraries folder.

**Comment by Llewellynvdm** [comment]
So here is the [code I used](https://github.com/vdm-io/Joomla-Component-Builder/blob/staging/libraries/jcb_powers/VDM.Joomla/src/Utilities/String/PluginHelper.php)... check the format of the braces and the order of the function variables.

I just refactored it a little more, this is how it will look like
```
/**
 * Making plugin folder name safe
 *
 * @input	string    $codeName   The name
 * @input	string    $group   The group name
 *
 * @returns string on success
 */
public static function safeFolderName($codeName, $group)
{
	// editors-xtd group plugins must have a class with plgButton<PluginName> structure
	if ($group === 'editors-xtd')
	{
		$group = 'Button';
	}

	return 'plg_' . strtolower($group) . '_' . strtolower(
		$codeName
	);
}

/**
 * Making plugin class name safe
 *
 * @input	string    $codeName   The name
 * @input	string    $group   The group name
 *
 * @returns string on success
 */
public static function safeClassName($codeName, $group)
{
	// editors-xtd group plugins must have a class with plgButton<PluginName> structure
	if ($group === 'editors-xtd')
	{
		$group = 'Button';
	}

	return 'Plg' . ucfirst($group) . ucfirst(
		$codeName
	);
}

/**
 * Making plugin install class name safe
 *
 * @input	string    $codeName   The name
 * @input	string    $group   The group name
 *
 * @returns string on success
 */
public static function safeInstallClassName($codeName, $group)
{
	// editors-xtd group plugins must have a class with plgButton<PluginName> structure
	if ($group === 'editors-xtd')
	{
		$group = 'Button';
	}

	return 'plg' . ucfirst($group) . ucfirst(
		$codeName
	) . 'InstallerScript';
}

/**
 * Making language prefix safe
 *
 * @input	string    $codeName   The name
 * @input	string    $group   The group name
 *
 * @returns string on success
 */
public static function safeLangPrefix($codeName, $group)
{
	// editors-xtd group plugins must have a class with plgButton<PluginName> structure
	if ($group === 'editors-xtd')
	{
		$group = 'Button';
	}

	return 'PLG_' . strtoupper($group) . strtoupper(
		$codeName
	);
}
```
I will close this PR now... @saman222 see you around in the next PR :+1:

**Pull request closed without merging**
