### PR TITLE
Major upgrade, with new filter system, and many bug fixes.

### PR DESCRIPTION
**Pull request by Llewellynvdm**
Pull Request for Issue gh-378, gh-609, gh-612, gh-616.

### Summary of Changes
- Fixed Warning: Invalid argument supplied for foreach() in ../html/libraries/cms/html/select.php on line 592 by adding empty select option.
- Resolve gh-609 to make sure that custom code set in a field that gets linked to a module will get added to the module.
- Removed legacy code from site views, that is no longer needed. Resolved gh-612
- Added filters above the admin list views to resolve gh-378
- Fixed the access filter in query.
- Fixed the array to int helper use.
- Added the correct language strings to category and access filters. gh-378
- Added sql to the uninstall sql to remove changes made to the assets table on uninstall of a component. resolved gh-616
- Fixed the file naming colution for the new filters. gh-378
- Use the new select language string in filters.
- Fixed category column naming issue in array query.
- Added the category code to the new filters area. gh-378
- Update the direction default the descending.
- Added getListViewDefaultOrdering method to compiler.
- Moved getFieldDatabaseName to the get class of the compiler.
- Updated the setFieldFilterListSet method.
- Imporved the filter query code to ignore empty values. gh-378
- Moved the default static code of the admin list views to compiler. gh-378
- Added the getCustomFieldCode, setFieldFilterSet, setFieldFilterListSet, setFilterFieldFile methods to the field compiler area.
- Refactored few other methods and added setDefaultSidebarFilterHelper, setCategorySidebarFilterHelper, setBatchDisplayHelper, setDefaultBatchHelper, setCategoryBatchHelper methods in the integration area of the compiler.
- Improved the header ser feature and added the setCategoryBatchHelper method. gh-378
- Add getFieldsetXML and getFieldXMLString method to build fields in compiler gh-378.
- Refactoring the compiler to use camelcase for view code names.
- Refactored the setFilterFields and setStoredId in the compiler as still part of the new filter option improvement. gh-378
- Updated the contribute area in README.
- Added the multi filter query method, and adapted the setFilterQuery method for the new filter options. gh-378
- Added the admin filter type switch to compiler gh-378.
- Moved the name_single and name_list to the view->name_list and view->name_list_code in the compiler (refactoring).
- Added the new field changes for the new filter implementation. gh-378
- Fixed gh-609 so that JS and CSS from fields are added to module.
- Also formatted the class with auto code reformat in phpstorm.

### Testing Instructions
Look over all the issues fixed, resolved and test accordingly.

### Expected result
That all issues are resolved.

### Documentation Changes Required
- How to use the new filters
- How to use the custom js and css in modules
- and more..

### CODE REVIEW

**Review by ohrionmartin — APPROVED** [review]
The new filters above the list views works like a charm and JCB's performance has improved with the new changes!

**Review by ohrionmartin — COMMENTED** [review]
**When I select multiple items in the list admin view, I get this NOTICE:**

Notice: Array to string conversion in /var/www/html/administrator/components/com_ehealth_portal/models/vmmcs.php on line 458

**When I set a custom fields's filter option to `Yes (multi)`, I get this error on compilation**

Screenshot from 2020-12-09 12-48-35

**When I Insert the above code snippet into the custom field, the component compiles successfully and when I try filtering (by selecting multiple items) in the admin list view I get this ERROR:**

Screenshot from 2020-12-09 13-08-36

**Comment by Llewellynvdm** [comment]
Okay so the issue was related to the getStoredId method, and is now resolved, please check again and let me know.

**Comment by ohrionmartin** [comment]
@Llewellynvdm 
All works perfectly now, PR is ready for merge!

**Comment by Llewellynvdm** [comment]
So the category filter was also now fixed, please confirm this.

**Comment by ohrionmartin** [comment]
Yes, everything works well now.. PR is now ready for merge!

**Pull request merged**
