### PR TITLE
Added CodeMirror to code areas all accross JCB

### PR DESCRIPTION
**Pull request by Llewellynvdm**
Pull Request for Issue gh-305 .

### Summary of Changes
Changed all/most textarea fields to editor fields with codemirror.

### Testing Instructions
Open all areas that has custom code areas and check if the values are editable and gets saved correctly.

### Expected result
That this transition from textarea fields to editor will improve JCB custom scripting.

### Actual result
New feature

### Documentation Changes Required
Well now we should have better control over the custom code, and so it should make things easier. We may need to make a tutorial to help those who do not know how to customize codemirror.

### CODE REVIEW

**Comment by ro-ot** [comment]
@Llewellynvdm I am still getting issues with the new editor. Checkout the dynamic get area, some of those php fields will not submit.

**Comment by Llewellynvdm** [comment]
I am working on this... very strange.

**Comment by ro-ot** [comment]
This look great! I will run a few test. What do you think about gh-312

**Comment by Llewellynvdm** [comment]
I also got the same error:

image

I am looking into it as we speak.

**Pull request merged**
