### PR TITLE
Fix Usergroup filter

### PR DESCRIPTION
**Pull request by tonypartridge**
This PR will fix the usergroup filter this section of code has been changed:

```
                {
                    $translation = false;
                    if (isset($this->selectionTranslationFixBuilder[$viewName_list]) && ComponentbuilderHelper::checkArray($this->selectionTranslationFixBuilder[$viewName_list]) && array_key_exists($filter['code'], $this->selectionTranslationFixBuilder[$viewName_list]))
                    {
                        $translation = true;
                    }
                    $function[] = PHP_EOL . $this->_t(1) . "protected function getThe" . $filter['function'] . "Selections()";
                    $function[] = $this->_t(1) . "{";
                    $function[] = $this->_t(2) . "//" . $this->setLine(__LINE__) . " Get a db connection.";
                    $function[] = $this->_t(2) . "\$db = JFactory::getDbo();";
                    $function[] = PHP_EOL . $this->_t(2) . "//" . $this->setLine(__LINE__) . " Create a new query object.";
                    $function[] = $this->_t(2) . "\$query = \$db->getQuery(true);";

                    // check if usergroup as we change to an object query
                    if ($filter['type'] === 'usergroup') {
                        $function[] = PHP_EOL . $this->_t(2) . "//" . $this->setLine(__LINE__) . " Select the text.";
                        $function[] = $this->_t(2) . "\$query->select(\$db->quoteName('g." . $filter['code'] . "', 'id'));";
                        $function[] = $this->_t(2) . "\$query->select(\$db->quoteName('ug.title', 'title'));";
                        $function[] = $this->_t(2) . "\$query->from(\$db->quoteName('#__" . $component . "_" . $filter['database'] . "', 'g'));";
                        $function[] = $this->_t(2) . "\$query->join('LEFT', \$db->quoteName('#__usergroups', 'ug') . ' ON (' . (\$db->quoteName('g." . $filter['code'] . "') . ' = ' . \$db->quoteName('ug.id') . ')'));";
                        $function[] = $this->_t(2) . "\$query->order(\$db->quoteName('title') . ' ASC');";
                        $function[] = $this->_t(2) . "\$query->group(\$db->quoteName('ug.id'));";
                        $function[] = PHP_EOL . $this->_t(2) . "//" . $this->setLine(__LINE__) . " Reset the query using our newly populated query object.";
                        $function[] = $this->_t(2) . "\$db->setQuery(\$query);";
                        $function[] = PHP_EOL . $this->_t(2) . "\$results = \$db->loadObjectList();";
                    } else {
                        $function[] = PHP_EOL . $this->_t(2) . "//" . $this->setLine(__LINE__) . " Select the text.";
                        $function[] = $this->_t(2) . "\$query->select(\$db->quoteName('" . $filter['code'] . "'));";
                        $function[] = $this->_t(2) . "\$query->from(\$db->quoteName('#__" . $component . "_" . $filter['database'] . "'));";
                        $function[] = $this->_t(2) . "\$query->order(\$db->quoteName('" . $filter['code'] . "') . ' ASC');";
                        $function[] = PHP_EOL . $this->_t(2) . "//" . $this->setLine(__LINE__) . " Reset the query using our newly populated query object.";
                        $function[] = $this->_t(2) . "\$db->setQuery(\$query);";
                        $function[] = PHP_EOL . $this->_t(2) . "\$results = \$db->loadColumn();";
                    }


                    $function[] = PHP_EOL . $this->_t(2) . "if (\$results)";
                    $function[] = $this->_t(2) . "{";

                    // check if translated value is used
                    if ($translation)
                    {
                        $function[] = $this->_t(3) . "//" . $this->setLine(__LINE__) . " get model";
                        $function[] = $this->_t(3) . "\$model = \$this->getModel();";
                    }
                    $function[] = $this->_t(3) . "\$results = array_unique(\$results);";
                    $function[] = $this->_t(3) . "\$_filter = array();";
                    $function[] = $this->_t(3) . "foreach (\$results as \$" . $filter['code'] . ")";
                    $function[] = $this->_t(3) . "{";


                    // check if translated vlaue is used
                    if ($translation)
                    {
                        $function[] = $this->_t(4) . "//" . $this->setLine(__LINE__) . " Translate the " . $filter['code'] . " selection";
                        $function[] = $this->_t(4) . "\$text = \$model->selectionTranslation(\$" . $filter['code'] . ",'" . $filter['code'] . "');";
                        $function[] = $this->_t(4) . "//" . $this->setLine(__LINE__) . " Now add the " . $filter['code'] . " and its text to the options array";
                        $function[] = $this->_t(4) . "\$_filter[] = JHtml::_('select.option', \$" . $filter['code'] . ", JText:" . ":_(\$text));";
                    }
                    elseif ($filter['type'] === 'user')
                    {
                        $function[] = $this->_t(4) . "//" . $this->setLine(__LINE__) . " Now add the " . $filter['code'] . " and its text to the options array";
                        $function[] = $this->_t(4) . "\$_filter[] = JHtml::_('select.option', \$" . $filter['code'] . ", JFactory::getUser(\$" . $filter['code'] . ")->name);";
                    }
                    else if ($filter['type'] === 'usergroup')
                    {
                        $function[] = $this->_t(4) . "//" . $this->setLine(__LINE__) . " Now add the " . $filter['code'] . " and its text to the options array";
                        $function[] = $this->_t(4) . "\$_filter[] = JHtml::_('select.option', \$" . $filter['code'] . "->id, \$" . $filter['code'] . "->title);";
                    }
                    else
                    {
                        $function[] = $this->_t(4) . "//" . $this->setLine(__LINE__) . " Now add the " . $filter['code'] . " and its text to the options array";
                        $function[] = $this->_t(4) . "\$_filter[] = JHtml::_('select.option', \$" . $filter['code'] . ", \$" . $filter['code'] . ");";
                    }
                    $function[] = $this->_t(3) . "}";
                    $function[] = $this->_t(3) . "return \$_filter;";
                    $function[] = $this->_t(2) . "}";
                    $function[] = $this->_t(2) . "return false;";
                    $function[] = $this->_t(1) . "}";
				}
```

I am struggling to get line endings right against your repo for some reason?  currently set to CRLF.

### CODE REVIEW

**Comment by Llewellynvdm** [comment]
I can't merge this request there is like crazy amount of lines changed. What editor are you using?

Can you not just pull the staging branch and then change just the lines above, and make a pull request with those, instead of auto formatting of the whole file in your IDE?

**Comment by Llewellynvdm** [comment]
I am working on Ubuntu, Netbeans.

**Comment by tonypartridge** [comment]
It's a line ending change, just using phpstorm. But it depends what system
you are developing on as to how you have stored them in JCB Github. Can you
confirm how they are stored?

My editor hasn't reformatted the fle.

*Sent with Shift
<https://tryshift.com/?utm_source=SentWithShift&utm_campaign=Sent%20with%20Shift%20Signature&utm_medium=Email%20Signature&utm_content=General%20Email%20Group>*

**Comment by Llewellynvdm** [comment]
So just to confirm I am on a pure Linux box, and so all files are saved on a UNIX file system. That is also my weakness I have never done development on Windows or any other... just Linux.

So can you try again?

**Comment by tonypartridge** [comment]
Ok so you are likely using LR, I saved are CRLF for cross compatibility.

I’m on Linux too, so will change it and do it again soon.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by pjdevries** [comment]
From what I can see, line endings are not consistent across the whole project. For instance: `script.php` in the root folder has LF line endings, wheras `componentbuilder.php` in the site folder has CRLF line endings.

**Comment by tonypartridge** [comment]
@Llewellynvdm  can you please update the projects line endings?

https://help.github.com/en/articles/dealing-with-line-endings

So you can have cross platform / user help.

**Comment by pjdevries** [comment]
And if you're like me and find the Github help somewhat confusing, this might be another good place to have a look:

[https://git-scm.com/book/it/v2/Customizing-Git-Git-Configuration#_code_core_autocrlf_code](https://git-scm.com/book/it/v2/Customizing-Git-Git-Configuration#_code_core_autocrlf_code)

**Comment by Llewellynvdm** [comment]
Okay we have an issue here, firstly the script.php file is auto generated, and in the compiler we are using `PHP_EOL` which means depending on what platform you compile the line-ending will change.

At the moment this pull request is dealing with the groups selecting filter and therefore not the place to resolve line endings.

So we can move this issue to its own place, yet to merge this pull request I need you to just push the update of the lines in question, and not change the whole file's line-endings.

**Comment by Llewellynvdm** [comment]
I can add the code, but then your contribution will be "unseen" I would like to give you the open door to actually contribute code. So I am giving this a few more days hoping to get a updated pull-request that only targets the code in question.

Secondly the current staging branch has moved, and so you will need to update your repo with the upstream.

**Comment by tonypartridge** [comment]
There you go! Used my mac in the end. Need to figure what GIT is going on ubuntu to my files!

**Comment by Llewellynvdm** [comment]
Okay I will pull this down and run some test. Thanks!

**Pull request merged**
